In [22]:
import numpy as np

In [23]:
a = np.array([2, 4, 6, 8, 10])
print(a)

[ 2  4  6  8 10]


In [24]:
a = np.arange(start = 1, stop = 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
p = np.zeros(shape=(3,3))
print(p)
print('\n')

q = np.ones(shape=(2,2))
print(q)
print('\n')

r = np.full(shape=(3,3), fill_value=5)
print(r)
print('\n')

s = np.eye(N=3)
print(s)
print('\n')

t = np.random.random(size=(3,3))
print(t)
print('\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]]


[[5 5 5]
 [5 5 5]
 [5 5 5]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0.99062931 0.16832301 0.34840514]
 [0.63921164 0.15345316 0.61350093]
 [0.44950312 0.42251182 0.06526324]]




In [26]:
a = np.arange(start=1,stop=10)
print(a.dtype)
print(type(a))
print(a.shape)

int32
<class 'numpy.ndarray'>
(9,)


In [27]:
a = np.array([[5,6], [7,8]])
print(a)
print('\n')
print(a[0,0])

[[5 6]
 [7 8]]


5


In [28]:
c = complex(42, 1)
print(c)

print(c.real)
print(c.imag)

(42+1j)
42.0
1.0


In [29]:
a = np.arange(12)
print(a)
print('\n')
new_arr = a.reshape(4,3)
print(new_arr)
print('\n')
new_arr2 = a.reshape(6,2)
print(new_arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [30]:
a = np.arange(12)
print(a)
print('\n')
a = a.reshape(3,4)
print(a)
print('\n')
a = a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
a = np.arange(12)
print(a)
print('\n')
a = a.reshape(3,4)
print(a)
print('\n')
a = a.ravel()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 0  1  2  3  4  5  6  7  8  9 10 11]


<h1>Note</h1>
<p>
Ravel and flatten do the same thing, that is converting n-dimensional arrays to 1-d arrays.
Difference is that flatten returns the actual array wheras ravel returns the reference of the array.
Hence, ravel is more fast.

In [32]:
a = np.arange(12)
a = a.reshape(4,3)
print(a)
print('\n')
a = a.transpose()
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [33]:
a = np.arange(12)
a = a.reshape(4,3)
print(a)
print('\n')
a.resize(6,2)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


<h1>Note</h1>

Reshape and resize do the same thing. 
The difference is that resize changes the original array and returns nothing wheras reshape does not change original array and only returns changed array

In [39]:
# Horizontal stacking

a1 = np.arange(1,10).reshape(3,3)
print(a1)
print('\n')

a2 = a1*2
print(a2)
print('\n')

a3 = np.hstack((a1, a2))
print(a3)
print('\n')

a4 = np.concatenate((a1, a2), axis=1)
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [40]:
# Vertical stacking

a1 = np.arange(1,10).reshape(3,3)
print(a1)
print('\n')

a2 = a1*2
print(a2)
print('\n')

a3 = np.vstack((a1, a2))
print(a3)
print('\n')

a4 = np.concatenate((a1, a2), axis=0)
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [41]:
# Depth stacking

a5 = np.dstack((a1, a2))
print(a5)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


In [42]:
# Column Stacking

a1 = np.arange(4,7)
print(a1)
print('\n')

a2 = 2*a1
print(a2)
print('\n')

a3 = np.column_stack((a1,a2))
print(a3)

[4 5 6]


[ 8 10 12]


[[ 4  8]
 [ 5 10]
 [ 6 12]]


In [43]:
# Row Stacking

a1 = np.arange(4,7)
print(a1)
print('\n')

a2 = 2*a1
print(a2)
print('\n')

a3 = np.row_stack((a1,a2))
print(a3)

[4 5 6]


[ 8 10 12]


[[ 4  5  6]
 [ 8 10 12]]


In [44]:
# Horizontal splitting

a = np.arange(1,10).reshape(3,3)
print(a)
print('\n')

a = np.hsplit(a,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [45]:
# Vertical splitting

a = np.arange(1,10).reshape(3,3)
print(a)
print('\n')

a = np.vsplit(a,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [46]:
a = np.arange(1,10).reshape(3,3)
print(a)
print('\n')

a = np.split(a, 3, axis=1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [47]:
a = np.arange(12)
print(a.dtype)

a = a.astype(float)
print(a.dtype)

int32
float64


In [48]:
a = np.arange(12)
print(a)
print('\n')
a = a.tolist()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [49]:
# Views and copies

a = np.arange(12).reshape(4,3)
print(a)
print('\n')

# Creates no copy
a_no_copy = a

# Creates deep copy
a_copy = a.copy()

# Creates shallow copy
a_view = a.view()

print("Original Array: ",id(a))
print("Assignment: ",id(a_no_copy))
print("Deep Copy: ",id(a_copy))
print("Shallow Copy(View): ",id(a_view))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Original Array:  1886299091312
Assignment:  1886299091312
Deep Copy:  1886299091472
Shallow Copy(View):  1886299091552


In [50]:
a[1] = [90,91,92]
#print(a)
print("Original Array: \n",a)
print("Assignment: \n",a_no_copy)
print("Deep Copy: \n",a_copy)
print("Shallow Copy(View): \n",a_view)

Original Array: 
 [[ 0  1  2]
 [90 91 92]
 [ 6  7  8]
 [ 9 10 11]]
Assignment: 
 [[ 0  1  2]
 [90 91 92]
 [ 6  7  8]
 [ 9 10 11]]
Deep Copy: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shallow Copy(View): 
 [[ 0  1  2]
 [90 91 92]
 [ 6  7  8]
 [ 9 10 11]]


<h1> Note </h1>

View is the original array only. Deep copy is a different object

In [51]:
a = np.arange(12)
print(a)
print(a[3:6])
print(a[3:])
print(a[-3:])
print(a[:6])
print(a[:-5])
print(a[2:8:2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[3 4 5]
[ 3  4  5  6  7  8  9 10 11]
[ 9 10 11]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6]
[2 4 6]


In [52]:
a = np.arange(12,50,3)
print(a)
print('\n')

a2 = a[a>30]
print(a2)

[12 15 18 21 24 27 30 33 36 39 42 45 48]


[33 36 39 42 45 48]


In [53]:
a = np.arange(16).reshape(4,4)
print(a)
print('\n')

indices = [1,2]
print(a[indices])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
row = np.array([1,2])
col = np.array([2,3])

print(a[row,col])

[ 6 11]


In [56]:
a1 = np.arange(1,5).reshape(2,2)
print(a1)
print('\n')

a2 = np.arange(11,15).reshape(2,2)
print(a2)

[[1 2]
 [3 4]]


[[11 12]
 [13 14]]


In [57]:
print(a1+a2)
print('\n')
print(a1-a2)
print('\n')
print(a1*a2)
print('\n')
print(a1/a2)

[[12 14]
 [16 18]]


[[-10 -10]
 [-10 -10]]


[[11 24]
 [39 56]]


[[0.09090909 0.16666667]
 [0.23076923 0.28571429]]


In [59]:
print(a1 + 100)

[[101 102]
 [103 104]]


In [60]:
print(a2 * 500)

[[5500 6000]
 [6500 7000]]


In [ ]:
# End